### ISSUE TITLE
Flex 布局：语法篇

### ISSUE THREAD

**Issue by linchwei** [linchwei/blog#8]
### Flex 布局是什么？
Flex 是 Flexible Box 的缩写，意为"弹性布局"，用来为盒状模型提供最大的灵活性。

任何一个容器都可以指定为 Flex 布局。
```css
.box{
  display: -webkit-flex; /* -webkit- */
  display: flex;
}
.box{
  display: -webkit-inline-flex; /* -webkit- */
  display: inline-flex;
}
```

**_注意，设为 Flex 布局以后，子元素的float、clear和vertical-align属性将失效。_**

### 基本概念
采用 Flex 布局的元素，称为 Flex 容器（flex container），简称"容器"。它的所有子元素自动成为容器成员，称为 Flex 项目（flex item），简称"项目"。
![flex base](https://github.com/linchwei/blog/blob/master/images/flex-base-1.png)
